var nchat_smiles_list =new Array(
	Array("v\\:\\)", nchat_smiles_url+"19.gif", "v:)"),
	Array("\\:\\)\\)", nchat_smiles_url+"21.gif", ":))"),
	Array("\\:\\)\\]", nchat_smiles_url+"100.gif", ":)]"),
	Array("\\:\\)&gt;-", nchat_smiles_url+"67.gif", ":)&gt;-"),
	Array("/\\:\\)", nchat_smiles_url+"23.gif", "/:)"),
	Array("\\^\\:\\)\\^", nchat_smiles_url+"77.gif", "^:)^"),
	Array("&gt;\\)\\:\\)", nchat_smiles_url+"48.gif", "&gt;):)"),
	Array("\\:\\)", nchat_smiles_url+"1.gif", ":)"),
	Array("\\:\\(\\(", nchat_smiles_url+"20.gif", ":(("),
	Array("3\\:-o", nchat_smiles_url+"50.gif", "3:-o"),
	Array("\\:\\(\\|\\)", nchat_smiles_url+"51.gif", ":(|)"),
	Array("\\:\\(", nchat_smiles_url+"2.gif", ":("),
	Array(";;\\)", nchat_smiles_url+"5.gif", ";;)"),
	Array(";\\)\\)", nchat_smiles_url+"71.gif", ";))"),
	Array(";\\)", nchat_smiles_url+"3.gif", ";)"),
	Array("&gt;\\:d&lt;", nchat_smiles_url+"6.gif", "&gt;:d&lt;"),
	Array("\\\\\\:d/", nchat_smiles_url+"69.gif", "\\:d/"),
	Array("\\:d", nchat_smiles_url+"4.gif", ":d"),
	Array("\\:-/", nchat_smiles_url+"7.gif", ":-/"),
	Array("\\:x", nchat_smiles_url+"8.gif", ":x"),
	Array("\\:&quot;&gt;", nchat_smiles_url+"9.gif", ":&quot;&gt;"),
	Array("&gt;\\:p", nchat_smiles_url+"47.gif", "&gt;:p"),
	Array("\\:p", nchat_smiles_url+"10.gif", ":p"),
	Array("\\:-\\*", nchat_smiles_url+"11.gif", ":-*"),
	Array("\\=\\(\\(", nchat_smiles_url+"12.gif", "=(("),
	Array("\\:-o", nchat_smiles_url+"13.gif", ":-o"),
	Array("~x\\(", nchat_smiles_url+"102.gif", "~x("),
	Array("x\\(", nchat_smiles_url+"14.gif", "x("),
	Array("~\\:&gt;", nchat_smiles_url+"52.gif", "~:&gt;"),
	Array("\\:&gt;", nchat_smiles_url+"15.gif", ":&gt;"),
	Array("b-\\)", nchat_smiles_url+"16.gif", "b-)"),
	Array("#\\:-s", nchat_smiles_url+"18.gif", "#:-s"),
	Array("\\:-ss", nchat_smiles_url+"42.gif", ":-ss"),
	Array("\\:-s", nchat_smiles_url+"17.gif", ":-s"),
	Array("\\(\\:\\|", nchat_smiles_url+"37.gif", "(:|"),
	Array("\\:\\|", nchat_smiles_url+"22.gif", ":|"),
	Array("rofl", nchat_smiles_url+"24.gif", "rofl"),
	Array("o\\:-\\)", nchat_smiles_url+"25.gif", "o:-)"),
	Array("\\:-bd", nchat_smiles_url+"113.gif", ":-bd"),
	Array("\\:-b", nchat_smiles_url+"26.gif", ":-b"),
	Array("\\=;", nchat_smiles_url+"27.gif", "=;"),
	Array("\\:-c", nchat_smiles_url+"101.gif", ":-c"),
	Array("\\:-h", nchat_smiles_url+"103.gif", ":-h"),
	Array("\\:-t", nchat_smiles_url+"104.gif", ":-t"),
	Array("8-&gt;", nchat_smiles_url+"105.gif", "8-&gt;"),
	Array("i-\\)", nchat_smiles_url+"28.gif", "i-)"),
	Array("8-\\|", nchat_smiles_url+"29.gif", "8-|"),
	Array("l-\\)", nchat_smiles_url+"30.gif", "l-)"),
	Array("\\:-&amp;", nchat_smiles_url+"31.gif", ":-&"),
	Array("\\:-\\$", nchat_smiles_url+"32.gif", ":-$"),
	Array("\\[-\\(", nchat_smiles_url+"33.gif", "[-("),
	Array("\\:o\\)", nchat_smiles_url+"34.gif", ":o)"),
	Array("8-\\}", nchat_smiles_url+"35.gif", "8-}"),
	Array("&lt;\\:-p", nchat_smiles_url+"36.gif", "&lt;:-p"),
	Array("\\=p~", nchat_smiles_url+"38.gif", "=p~"),
	Array("\\:-\\?\\?", nchat_smiles_url+"106.gif", ":-??"),
	Array("\\:-\\?", nchat_smiles_url+"39.gif", ":-?"),
	Array("#-o", nchat_smiles_url+"40.gif", "#-o"),
	Array("\\=d&gt;", nchat_smiles_url+"41.gif", "=d&gt;"),
	Array("@-\\)", nchat_smiles_url+"43.gif", "@-)"),
	Array("\\:\\^o", nchat_smiles_url+"44.gif", ":^o"),
	Array("\\:-w", nchat_smiles_url+"45.gif", ":-w"),
	Array("\\:-&lt;", nchat_smiles_url+"46.gif", ":-&lt;"),
	Array("x_x", nchat_smiles_url+"109.gif", "x_x"),
	Array("\\:\\!\\!", nchat_smiles_url+"110.gif", ":!!"),
	Array("\\\\m/", nchat_smiles_url+"111.gif", "\\m/"),
	Array("\\:-q", nchat_smiles_url+"112.gif", ":-q"),
	Array("\\^#\\(\\^", nchat_smiles_url+"114.gif", "^#(^"),
	Array("\\:bz", nchat_smiles_url+"115.gif", ":bz"),
	Array("\\:o3", nchat_smiles_url+"108.gif", ":o3"),
	Array("%-\\(", nchat_smiles_url+"107.gif", "%-("),
	Array("\\:@\\)", nchat_smiles_url+"49.gif", ":@)"),
	Array("@\\};-", nchat_smiles_url+"53.gif", "@};-"),
	Array("8-x", nchat_smiles_url+"59.gif", "8-x"),
	Array("\\:-l", nchat_smiles_url+"62.gif", ":-l"),
	Array("\\[-o&lt;", nchat_smiles_url+"63.gif", "[-o&lt;"),
	Array("\\$-\\)", nchat_smiles_url+"64.gif", "$-)"),
	Array("\\:-&quot;", nchat_smiles_url+"65.gif", ":-&quot;"),
	Array("b-\\(", nchat_smiles_url+"66.gif", "b-("),
	Array("\\[-x", nchat_smiles_url+"68.gif", "[-x"),
	Array("&gt;\\:/", nchat_smiles_url+"70.gif", "&gt;:/"),
	Array("\\:-@", nchat_smiles_url+"76.gif", ":-@"),
	Array("\\:-j", nchat_smiles_url+"78.gif", ":-j"),
	Array("\\(\\*\\)", nchat_smiles_url+"79.gif", "(*)"),
//	Array("\\(\\Y\\)", "http://www.brothersinhonour.com/images/smilies/smiley_champagne.gif", "(Y)"),	// dead: 404, file removed from host
	Array("\\(\\:B\\)", nchat_smiles_url+"beer-chugger.gif", "(:B)"),
	Array("\\(\\:Z\\)", nchat_smiles_url+"drunk.gif", "(:Z)"),
//	Array("\\(\\:R\\)", "/Smileys/champagne-bottle-accident-smiley-emoticon.gif", "(:R)"),	// dead: source host gone, no local copy of champagne-bottle-accident-smiley-emoticon.gif
//	Array("\\(\\:W\\)", "/Smileys/drinking-red-wine.gif", "(:W)"),	// dead: source host gone, no local copy of drinking-red-wine.gif
//	Array("\\(\\:C\\)", "http://www.directsmiley.com/cat/1/1_4_63.gif", "(:C)"),	// dead: domain parked, 301s to m.ask.com
	Array("\\(\\:H\\)", nchat_smiles_url+"barman.gif", "(:H)"),
	Array("\\(\\:M\\)", nchat_smiles_url+"arg04.gif", "(:M)"),
//	Array("\\(\\:Q\\)", "http://pwi-forum.perfectworld.com/images/smilies/byeby.gif", "(:Q)"),	// dead: domain no longer resolves
//	Array("\\(\\:Y\\)", "/Smileys/th_bull_fight.gif", "(:Y)"),	// dead: source host gone, no local copy of th_bull_fight.gif
//	Array("\\(\\:G\\)", "/Smileys/grizzly.jpg", "(:G)"),	// dead: source host gone, no local copy of grizzly.jpg
//	Array("\\(\\:L\\)", "/Smileys/laser-blaster.gif", "(:L)"),	// dead: source host gone, no local copy of laser-blaster.gif
//	Array("\\(\\:T\\)", "/Smileys/tank-2", "(:T)"),	// dead: source host gone, no local copy of tank-2
//	Array("\\(\\:A\\)", "/Smileys/rocket-launcher.gif", "(:A)"),	// dead: source host gone, no local copy of rocket-launcher.gif
//	Array("\\(\\:J\\)", "/Smileys/rocket-launcher-1.gif", "(:J)"),	// dead: source host gone, no local copy of rocket-launcher-1.gif
//	Array("\\(\\:E\\)", "/Smileys/rambo.gif", "(:E)"),	// dead: source host gone, no local copy of rambo.gif
//	Array("\\(\\:F\\)", "/Smileys/ouch.gif", "(:F)"),	// dead: source host gone, no local copy of ouch.gif
//	Array("\\(\\:K\\)", "/Smileys/give_present.gif", "(:K)"),	// dead: source host gone, no local copy of give_present.gif
//	Array("\\(\\:N\\)", "/Smileys/MechanicalBullSmiley.gif", "(:N)"),	// dead: source host gone, no local copy of MechanicalBullSmiley.gif
//	Array("\\(\\:S\\)", "/Smileys/googlesearch.jpg", "(:S)"),	// dead: source host gone, no local copy of googlesearch.jpg
//	Array("\\(\\:U\\)", "/Smileys/pray.jpeg", "(:U)"),	// dead: source host gone, no local copy of pray.jpeg
	Array("\\%F", nchat_smiles_url+"psychic.gif", "%F"),
	Array("\\%\\(", nchat_smiles_url+"voodoo.gif", "%("),
	Array("&lt;\\:\\)", nchat_smiles_url+"wizard.gif", "<:)"),
	Array("\\[\\:\\)", nchat_smiles_url+"sheikh.gif", "[:)"),
	Array("\\:\\)\\.\\.", nchat_smiles_url+"drool.gif", ":).."),
	Array("\\-\\$\\-", nchat_smiles_url+"flying-money.gif", "-$-"),
	Array("\\-\\+\\-", nchat_smiles_url+"storm.gif", "-+-"),
	Array("\\\\oo/", nchat_smiles_url+"tanker_transparent.png", "\\oo/"),
//	Array("\\%\\)", "/Smileys/gammelserver/drunk-smiley-emoticon.gif", "%)"),	// dead: source host gone, no local copy of drunk-smiley-emoticon.gif
	Array("\\%o\\)", nchat_smiles_url+"drunk_smiley.gif", "%o)"),
	Array("\\(N\\)", nchat_smiles_url+"Wave%20norwegian%20flag%20small.gif", "(N)"),
	Array("\\(KD\\)", nchat_smiles_url+"Wave%20kurdistan%20flag%20small.gif", "(KD)"),
	Array("\\(DNO\\)", nchat_smiles_url+"Wave%20DNO%20flag%20small.gif", "(DNO)")
);
